create table public.loyalty_programs (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  is_active boolean not null default false,
  earn_mode text not null default 'points_per_euro' check (earn_mode in ('points_per_euro','orders','custom')),
  points_per_euro numeric(10,2) not null default 1 check (points_per_euro >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id)
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  auth_user_id uuid null references auth.users(id) on delete set null,
  name text,
  phone text,
  email text,
  marketing_email boolean not null default false,
  marketing_sms boolean not null default false,
  marketing_push boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index customers_restaurant_auth_user_uidx on public.customers(restaurant_id, auth_user_id) where auth_user_id is not null;
create index customers_restaurant_created_idx on public.customers(restaurant_id, created_at desc);

create table public.loyalty_accounts (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  balance_points bigint not null default 0 check (balance_points >= 0),
  lifetime_earned_points bigint not null default 0 check (lifetime_earned_points >= 0),
  lifetime_redeemed_points bigint not null default 0 check (lifetime_redeemed_points >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, customer_id)
);

create table public.loyalty_ledger (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  loyalty_account_id uuid not null references public.loyalty_accounts(id) on delete cascade,
  amount_points bigint not null check (amount_points <> 0),
  transaction_type text not null check (transaction_type in ('ORDER_EARN','REWARD_REDEEM','BONUS','ADJUSTMENT','EXPIRATION')),
  reference_type text,
  reference_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index loyalty_accounts_restaurant_idx on public.loyalty_accounts(restaurant_id, updated_at desc);
create index loyalty_ledger_account_created_idx on public.loyalty_ledger(loyalty_account_id, created_at desc);
create index loyalty_ledger_restaurant_customer_idx on public.loyalty_ledger(restaurant_id, customer_id, created_at desc);

create table public.loyalty_rewards (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  description text,
  cost_points bigint not null check (cost_points > 0),
  reward_type text not null check (reward_type in ('FIXED_DISCOUNT','PERCENT_DISCOUNT','FREE_PRODUCT','CUSTOM')),
  reward_value jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index loyalty_rewards_restaurant_active_idx on public.loyalty_rewards(restaurant_id, is_active);

create table public.marketing_consents (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  channel text not null check (channel in ('EMAIL','SMS','PUSH')),
  granted boolean not null,
  source text not null default 'customer',
  granted_at timestamptz,
  withdrawn_at timestamptz,
  created_at timestamptz not null default now(),
  unique (restaurant_id, customer_id, channel)
);

create index marketing_consents_customer_idx on public.marketing_consents(restaurant_id, customer_id);

alter table public.loyalty_programs enable row level security;
alter table public.customers enable row level security;
alter table public.loyalty_accounts enable row level security;
alter table public.loyalty_ledger enable row level security;
alter table public.loyalty_rewards enable row level security;
alter table public.marketing_consents enable row level security;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create trigger loyalty_programs_updated_at before update on public.loyalty_programs for each row execute function public.set_updated_at();
create trigger customers_updated_at before update on public.customers for each row execute function public.set_updated_at();
create trigger loyalty_accounts_updated_at before update on public.loyalty_accounts for each row execute function public.set_updated_at();
create trigger loyalty_rewards_updated_at before update on public.loyalty_rewards for each row execute function public.set_updated_at();
