create table public.marketing_consent_events (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  channel text not null check (channel in ('EMAIL','SMS','PUSH')),
  granted boolean not null,
  source text not null default 'customer',
  created_at timestamptz not null default now()
);

create index marketing_consent_events_customer_idx on public.marketing_consent_events(restaurant_id, customer_id, created_at desc);

alter table public.marketing_consent_events enable row level security;

create policy marketing_consent_events_admin_select on public.marketing_consent_events
for select to authenticated
using (public.is_restaurant_admin() and restaurant_id = public.current_restaurant_id());

create policy marketing_consent_events_self_select on public.marketing_consent_events
for select to authenticated
using (exists (select 1 from public.customers c where c.id = customer_id and c.auth_user_id = auth.uid() and c.restaurant_id = marketing_consent_events.restaurant_id));

create or replace function public.prevent_loyalty_ledger_mutation() returns trigger language plpgsql security definer set search_path = public as $$
begin
  raise exception 'loyalty_ledger is append-only';
end;
$$;

create trigger loyalty_ledger_no_update before update on public.loyalty_ledger for each row execute function public.prevent_loyalty_ledger_mutation();
create trigger loyalty_ledger_no_delete before delete on public.loyalty_ledger for each row execute function public.prevent_loyalty_ledger_mutation();
